name = "platform-maker"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "platform-maker-db"
database_id = "2980a6aa-1ef6-435c-914b-c3f64fe5443b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "pm-assets"
